import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

import "./reset.scss";
import "./globals.scss";
import { Theme } from "@radix-ui/themes";

const notoSansJP = Noto_Sans_JP({
    subsets: ["latin"],
    variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
    title: "Love dump",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="jp">
            <head>
                <link rel="manifest" href="/manifest.json" />
                <link rel="apple-touch-icon" href="/icon.png"></link>
                <meta name="theme-color" content="#e3eefa" />
            </head>
            <body className={notoSansJP.className}>
                <Theme>{children}</Theme>
            </body>
        </html>
    );
}
